DROP TABLE PLAYER IF EXISTS;

CREATE TABLE PLAYER (
  USERNAME        VARCHAR(100) NOT NULL,
  BALANCE_VERSION INTEGER      NOT NULL,
  BALANCE         DECIMAL      NOT NULL,
  UNIQUE (USERNAME, BALANCE_VERSION)

);